// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20220521000245_PopulaBb")]
    partial class PopulaBb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta ciza",
                            ImageUrl = "https://cf.shopee.com.br/file/90c8d140e4df5886b7d1b266ab11714f",
                            Name = "Mamonas",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta ciza",
                            ImageUrl = "https://img.elo7.com.br/product/zoom/1EAC4D6/camiseta-rock-guitarrista-t-shirt.jpg",
                            Name = "Rock",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta ciza",
                            ImageUrl = "https://hmrock.com.br/wp-content/uploads/2018/12/caveira.jpg",
                            Name = "Rock",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta ciza",
                            ImageUrl = "https://cea.vtexassets.com/arquivos/ids/22173183/Camiseta-Masculina--Rock-n--Roll--Guitarra-Flocada-Manga-Curta-Gola-Careca-Preta-9966708-Preto_2.jpg?v=637430282968630000",
                            Name = "Guitar",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta ciza",
                            ImageUrl = "https://images.fatum.com.br/site/produtos/123.jpg?losslevel=1&v=10.4",
                            Name = "Kiss",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
